require_relative 'boot'

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module SecretProgram
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.1

    config.relative_url_root = "/secret_program"

    config.after_initialize do
      $e_hash = Hash.new
      $e_hash[" "] = "0"
      $e_hash["!"] = "]"
      $e_hash["\""] = "J"
      $e_hash["#"] = "8"
      $e_hash["$"] = "N"
      $e_hash["%"] = "c"
      $e_hash["&"] = "S"
      $e_hash["'"] = "j"
      $e_hash["("] = "}"
      $e_hash[")"] = "h"
      $e_hash["*"] = "F"
      $e_hash["+"] = "i"
      $e_hash[","] = "u"
      $e_hash["-"] = "v"
      $e_hash["."] = "a"
      $e_hash["/"] = "\""
      $e_hash["0"] = "n"
      $e_hash["1"] = "m"
      $e_hash["2"] = "o"
      $e_hash["3"] = "x"
      $e_hash["4"] = "6"
      $e_hash["5"] = "r"
      $e_hash["6"] = "I"
      $e_hash["7"] = "+"
      $e_hash["8"] = "Y"
      $e_hash["9"] = "f"
      $e_hash[":"] = "\\"
      $e_hash[";"] = "@"
      $e_hash["<"] = "G"
      $e_hash["="] = "W"
      $e_hash[">"] = "K"
      $e_hash["?"] = "*"
      $e_hash["@"] = " "
      $e_hash["A"] = "Q"
      $e_hash["B"] = "B"
      $e_hash["C"] = "'"
      $e_hash["D"] = "Z"
      $e_hash["E"] = "#"
      $e_hash["F"] = "P"
      $e_hash["G"] = "T"
      $e_hash["H"] = ")"
      $e_hash["I"] = "9"
      $e_hash["J"] = "-"
      $e_hash["K"] = "s"
      $e_hash["L"] = "{"
      $e_hash["M"] = "p"
      $e_hash["N"] = "?"
      $e_hash["O"] = "/"
      $e_hash["P"] = "q"
      $e_hash["Q"] = "7"
      $e_hash["R"] = ":"
      $e_hash["S"] = "A"
      $e_hash["T"] = "^"
      $e_hash["U"] = "["
      $e_hash["V"] = "L"
      $e_hash["W"] = "."
      $e_hash["X"] = "("
      $e_hash["Y"] = "E"
      $e_hash["Z"] = "2"
      $e_hash["["] = "1"
      $e_hash["\\"] = ";"
      $e_hash["]"] = "~"
      $e_hash["^"] = "="
      $e_hash["_"] = "&"
      $e_hash["`"] = "d"
      $e_hash["a"] = "k"
      $e_hash["b"] = "y"
      $e_hash["c"] = "5"
      $e_hash["d"] = "b"
      $e_hash["e"] = "D"
      $e_hash["f"] = "C"
      $e_hash["g"] = "H"
      $e_hash["h"] = "U"
      $e_hash["i"] = "!"
      $e_hash["j"] = "3"
      $e_hash["k"] = "`"
      $e_hash["l"] = "M"
      $e_hash["m"] = "|"
      $e_hash["n"] = "X"
      $e_hash["o"] = "z"
      $e_hash["p"] = "t"
      $e_hash["q"] = "w"
      $e_hash["r"] = "e"
      $e_hash["s"] = "l"
      $e_hash["t"] = "<"
      $e_hash["u"] = "R"
      $e_hash["v"] = "O"
      $e_hash["w"] = "$"
      $e_hash["x"] = "%"
      $e_hash["y"] = ">"
      $e_hash["z"] = ","
      $e_hash["{"] = "V"
      $e_hash["|"] = "_"
      $e_hash["}"] = "4"
      $e_hash["~"] = "g"
      $d_hash = Hash.new
      $d_hash["0"] = " "
      $d_hash["]"] = "!"
      $d_hash["J"] = "\""
      $d_hash["8"] = "#"
      $d_hash["N"] = "$"
      $d_hash["c"] = "%"
      $d_hash["S"] = "&"
      $d_hash["j"] = "'"
      $d_hash["}"] = "("
      $d_hash["h"] = ")"
      $d_hash["F"] = "*"
      $d_hash["i"] = "+"
      $d_hash["u"] = ","
      $d_hash["v"] = "-"
      $d_hash["a"] = "."
      $d_hash["\""] = "/"
      $d_hash["n"] = "0"
      $d_hash["m"] = "1"
      $d_hash["o"] = "2"
      $d_hash["x"] = "3"
      $d_hash["6"] = "4"
      $d_hash["r"] = "5"
      $d_hash["I"] = "6"
      $d_hash["+"] = "7"
      $d_hash["Y"] = "8"
      $d_hash["f"] = "9"
      $d_hash["\\"] = ":"
      $d_hash["@"] = ";"
      $d_hash["G"] = "<"
      $d_hash["W"] = "="
      $d_hash["K"] = ">"
      $d_hash["*"] = "?"
      $d_hash[" "] = "@"
      $d_hash["Q"] = "A"
      $d_hash["B"] = "B"
      $d_hash["'"] = "C"
      $d_hash["Z"] = "D"
      $d_hash["#"] = "E"
      $d_hash["P"] = "F"
      $d_hash["T"] = "G"
      $d_hash[")"] = "H"
      $d_hash["9"] = "I"
      $d_hash["-"] = "J"
      $d_hash["s"] = "K"
      $d_hash["{"] = "L"
      $d_hash["p"] = "M"
      $d_hash["?"] = "N"
      $d_hash["/"] = "O"
      $d_hash["q"] = "P"
      $d_hash["7"] = "Q"
      $d_hash[":"] = "R"
      $d_hash["A"] = "S"
      $d_hash["^"] = "T"
      $d_hash["["] = "U"
      $d_hash["L"] = "V"
      $d_hash["."] = "W"
      $d_hash["("] = "X"
      $d_hash["E"] = "Y"
      $d_hash["2"] = "Z"
      $d_hash["1"] = "["
      $d_hash[";"] = "\\"
      $d_hash["~"] = "]"
      $d_hash["="] = "^"
      $d_hash["&"] = "_"
      $d_hash["d"] = "`"
      $d_hash["k"] = "a"
      $d_hash["y"] = "b"
      $d_hash["5"] = "c"
      $d_hash["b"] = "d"
      $d_hash["D"] = "e"
      $d_hash["C"] = "f"
      $d_hash["H"] = "g"
      $d_hash["U"] = "h"
      $d_hash["!"] = "i"
      $d_hash["3"] = "j"
      $d_hash["`"] = "k"
      $d_hash["M"] = "l"
      $d_hash["|"] = "m"
      $d_hash["X"] = "n"
      $d_hash["z"] = "o"
      $d_hash["t"] = "p"
      $d_hash["w"] = "q"
      $d_hash["e"] = "r"
      $d_hash["l"] = "s"
      $d_hash["<"] = "t"
      $d_hash["R"] = "u"
      $d_hash["O"] = "v"
      $d_hash["$"] = "w"
      $d_hash["%"] = "x"
      $d_hash[">"] = "y"
      $d_hash[","] = "z"
      $d_hash["V"] = "{"
      $d_hash["_"] = "|"
      $d_hash["4"] = "}"
      $d_hash["g"] = "~"
    end

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
  end
end
